### ISSUE TITLE
Un eclipse debería modificar la fuerza oscura de forma general, no particular para cada personaje

### ISSUE THREAD

**Issue by natoszme** [nahuelDolian/TPObjetos#10]
O sea que si lo modelamos así:
```
method eclipse(){
	valorFuerzaOscura = (self.valorFuerzaOscura()) * 2
}
```
el eclipse ocurriría para un personaje particular (aquel al que se le envíe el mensaje eclipse).
Pero en la entrega 1 dice 

> El valor de la fuerza oscura es un cálculo global que afecta a todos (incluído Rolando).

**Comment by lublanco** [comment]
ya modifique ahora es un calculo global

**Comment by lublanco** [comment]
cerré sin querer
