### ISSUE TITLE
Debo poder crear cotas de malla con aportes de poder distintos

### ISSUE THREAD

**Issue by natoszme** [nahuelDolian/TPObjetos#11]
Y de momento, no se puede

**Comment by lublanco** [comment]
decis al momento de utilizar el constructor en la armadura?

como esta en el codigo se puede hacer lo siguiente

(Ej)

const otraArmadura = new Armadura(rolando, 5, cotaDeMalla)
otraArmadura.cambiarRefuerzo(6)

el mensaje cambiarRefuerzo solo lo entiende el refuerzo de cota de malla

object cotaDeMalla{
	var dueno
	var refuerzo = 1
	var precioEnMonedas 
	
	method refuerzo(nuevoValor){
		refuerzo = nuevoValor
	}
	method aportar(){
		return refuerzo
	}
	method dueno(unDueno){
		dueno=unDueno
	}
}

Crees que hay que cambiarlo?

**Comment by natoszme** [comment]
Pasa que como la cota de malla es un WKO, al cambiar el refuerzo, va a cambiar el de todas las otras cotas de malla que estén en otras armaduras. Y entiendo que el enunciado quiere poder tener simultáneamente cotas de mallas como distintos valores

**Comment by lublanco** [comment]
si acabo de cambiarlo

**Comment by lublanco** [comment]
class CotaDeMalla{
	var property dueno
	var property refuerzo
	
	constructor(elegirValorRefuerzo){
		refuerzo = elegirValorRefuerzo
		dueno = null
	}
	method aportar(){
		return refuerzo
	}
}
