### ISSUE TITLE
Puede haber inconsistencias si dos armaduras de dos personajes distintos, tienen la bendición como refuerzo

### ISSUE THREAD

**Issue by natoszme** [nahuelDolian/TPObjetos#13]
El enunciado tira la aclaración

> Bendición: Igual que en la primera entrega (pero recordar que ahora hay muchos personajes).

Y por cómo lo tienen ahora, seteando el dueño a un único objeto `bendicion `, puede pasar lo siguiente:
si se lo seteo a una armadura que es de rolando va a tener a rolando como dueño, hasta acá todo ok.
Si después quiero agregarle otra armadura a otro personaje con bendicion como refuerzo, voy a volver a setear el personaje, produciendo que **la armadura de rolando tenga una bendicion cuyo duenio no es él** (porque lo acabamos de cambiar). Esto no es consistente!

Lo que me lleva a pensar: podríamos resolver esto directamente sin tener a los duenios en cada una de las armaduras? Qué me aporta tenerlos? Y, si cuando le queremos mandar un mensaje a cada artefacto de lucha, le pasamos al duenio como parámetro?

Esto lo hablamos al final de la entrega pasada. Chequéenlo!

**Comment by PiruKaren** [comment]
Sacamos dueño como atributo y lo estamos pasando como variable..
