### ISSUE TITLE
"El hechizo básico sigue existiendo y puede ser el preferido de varios personajes a la vez"

### ISSUE THREAD

**Issue by natoszme** [nahuelDolian/TPObjetos#4]
Y si lo modelamos con una clase, al hacer un new HechizoBasico para agregárselo a cada personaje, tendríamos que cada uno de ellos referencia a otro hechizo básico, **con iguales atributos entre si pero distinta identidad.**

De la entrega 1 conocemos un concepto que nos puede ayudar a modelarlo. Cuál?

**Comment by lublanco** [comment]
ahora el HechizoBasico puede ser el preferido de varios personajes al mismo tiempo
