### ISSUE TITLE
Qué aporta esto?

### ISSUE THREAD

**Issue by natoszme** [nahuelDolian/TPObjetos#7]
```
class Espada inherits ArmaBlanca{
	}
	
class Hacha inherits ArmaBlanca{
	}
	
class Lanza inherits ArmaBlanca{
	}	 
```

Si el enunciado habla sobre que hay muchas armas que aportan 3

**Comment by nahuelDolian** [comment]
Claro, lo que nosotros quisimos hacer es "agrupar" las espadas, hachas y lanzas..
Quizás no hace falta crear éstas "subclases" ya que todas tienen el mismo comportamiento y ninguna difiere de la otra... o quizás si, la verdad es algo sobre el diseño que no me cierra...
No se si no entiendo la corrección, o qué...
pero la clase ArmaBlanca debe estar si o si, pues sino repetiriamos lógica..

**Comment by natoszme** [comment]
Si lo que queremos es agrupar todas las "armas blancas", y todas tienen igual comportamiento, por qué no ir creando distintas instancias de esa clase? Haciendo varios new de la misma.

Como decías vos, si ninguna difiere de la otra, no tiene mucho sentido pararse y decir "che, ésta de acá es una Espada (por ejemplo) pero la pongo para que sepan que exista (que es lo que están haciendo en herencia a ArmaBlanca)". Directamente podemos usar lo de arriba.

Se entiende? Esto es importante

**Comment by lublanco** [comment]
Ya modifique
