### ISSUE TITLE
Por qué guardar el dueño de la Mascara?

### ISSUE THREAD

**Issue by natoszme** [nahuelDolian/TPObjetos#8]
Para preguntarle el valor de la fuerza oscura, como acá?

```
method calcularSuAporte(){
	return (dueno.valorFuerzaOscura()/2)*indiceDeOscuridad
}
```

Pero veamos cómo resuelve el dueño la obtención de la misma: `fuerzaOscura.valor()`

Entonces, si la Mascara puede consultar directamente el valor de la fuerza oscura mandándole un mensaje a ese WKO, por qué poner el duenio en el medio?

**Comment by lublanco** [comment]
ya modifique
