### ISSUE TITLE
Seguimos teniendo dos métodos para lo mismo: damePoder() y aportar en artefactosDeLucha

### ISSUE THREAD

**Issue by natoszme** [nahuelDolian/TPObjetos#9]
Esto ya lo charlamos varias veces, pero si no queda claro digan!
El problema era que el espejo podía tener problemas de loops si es el único elemento que tiene el personaje. Pero realmente queremos **obligar a todo el resto los objetos que cumplen esa interfaz** a definir el método
```
method damePoder() {
	return self.aportar()
}
```
que es un "pasamanos" para resolver **un problema que es propio del espejo**?

**Comment by nahuelDolian** [comment]
Si!, yo por lo menos lo entendí, veremos el resto..
Lo modifiqué en artefactosDeLucha.wlk , y tambien en Personaje.wlk, ya que usaba el damePoder()

**Comment by natoszme** [comment]
En artefactos de lucha sigue estando, en todo lo que no es el espejo

**Comment by lublanco** [comment]
ya los saque ahora solo tiene aportar()
